# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key_figure_card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils.card_header_pb2 as card__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='key_figure_card.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15key_figure_card.proto\x1a\x11\x63\x61rd_header.proto\"L\n\rKeyFigureCard\x12\x1b\n\x06header\x18\x01 \x01(\x0b\x32\x0b.CardHeader\x12\x1e\n\nkeyFigures\x18\x02 \x03(\x0b\x32\n.KeyFigure\"\x8b\x03\n\tKeyFigure\x12\x1d\n\x04rank\x18\x01 \x01(\x0e\x32\x0f.KeyFigure.Rank\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x10\n\x08\x64\x65\x63imals\x18\x03 \x01(\x05\x12\x1f\n\x05trend\x18\x04 \x01(\x0e\x32\x10.KeyFigure.Trend\x12/\n\rtrendSemantic\x18\x05 \x01(\x0e\x32\x18.KeyFigure.TrendSemantic\"F\n\x04Rank\x12\x14\n\x10UNSPECIFIED_RANK\x10\x00\x12\x0b\n\x07PRIMARY\x10\x01\x12\r\n\tSECONDARY\x10\x02\x12\x0c\n\x08TERTIARY\x10\x03\"J\n\x05Trend\x12\x15\n\x11UNSPECIFIED_TREND\x10\x00\x12\n\n\x06STABLE\x10\x01\x12\x0e\n\nINCREASING\x10\x02\x12\x0e\n\nDECREASING\x10\x03\"X\n\rTrendSemantic\x12\x1e\n\x1aUNSPECIFIED_TREND_SEMANTIC\x10\x00\x12\x0b\n\x07NEUTRAL\x10\x01\x12\x0c\n\x08POSITIVE\x10\x02\x12\x0c\n\x08NEGATIVE\x10\x03\x62\x06proto3'
  ,
  dependencies=[card__header__pb2.DESCRIPTOR,])



_KEYFIGURE_RANK = _descriptor.EnumDescriptor(
  name='Rank',
  full_name='KeyFigure.Rank',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_RANK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRIMARY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECONDARY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TERTIARY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=282,
  serialized_end=352,
)
_sym_db.RegisterEnumDescriptor(_KEYFIGURE_RANK)

_KEYFIGURE_TREND = _descriptor.EnumDescriptor(
  name='Trend',
  full_name='KeyFigure.Trend',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_TREND', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STABLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INCREASING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DECREASING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=354,
  serialized_end=428,
)
_sym_db.RegisterEnumDescriptor(_KEYFIGURE_TREND)

_KEYFIGURE_TRENDSEMANTIC = _descriptor.EnumDescriptor(
  name='TrendSemantic',
  full_name='KeyFigure.TrendSemantic',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_TREND_SEMANTIC', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEUTRAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POSITIVE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEGATIVE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=430,
  serialized_end=518,
)
_sym_db.RegisterEnumDescriptor(_KEYFIGURE_TRENDSEMANTIC)


_KEYFIGURECARD = _descriptor.Descriptor(
  name='KeyFigureCard',
  full_name='KeyFigureCard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='KeyFigureCard.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyFigures', full_name='KeyFigureCard.keyFigures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=120,
)


_KEYFIGURE = _descriptor.Descriptor(
  name='KeyFigure',
  full_name='KeyFigure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank', full_name='KeyFigure.rank', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='KeyFigure.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='decimals', full_name='KeyFigure.decimals', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trend', full_name='KeyFigure.trend', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trendSemantic', full_name='KeyFigure.trendSemantic', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KEYFIGURE_RANK,
    _KEYFIGURE_TREND,
    _KEYFIGURE_TRENDSEMANTIC,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=518,
)

_KEYFIGURECARD.fields_by_name['header'].message_type = card__header__pb2._CARDHEADER
_KEYFIGURECARD.fields_by_name['keyFigures'].message_type = _KEYFIGURE
_KEYFIGURE.fields_by_name['rank'].enum_type = _KEYFIGURE_RANK
_KEYFIGURE.fields_by_name['trend'].enum_type = _KEYFIGURE_TREND
_KEYFIGURE.fields_by_name['trendSemantic'].enum_type = _KEYFIGURE_TRENDSEMANTIC
_KEYFIGURE_RANK.containing_type = _KEYFIGURE
_KEYFIGURE_TREND.containing_type = _KEYFIGURE
_KEYFIGURE_TRENDSEMANTIC.containing_type = _KEYFIGURE
DESCRIPTOR.message_types_by_name['KeyFigureCard'] = _KEYFIGURECARD
DESCRIPTOR.message_types_by_name['KeyFigure'] = _KEYFIGURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyFigureCard = _reflection.GeneratedProtocolMessageType('KeyFigureCard', (_message.Message,), {
  'DESCRIPTOR' : _KEYFIGURECARD,
  '__module__' : 'key_figure_card_pb2'
  # @@protoc_insertion_point(class_scope:KeyFigureCard)
  })
_sym_db.RegisterMessage(KeyFigureCard)

KeyFigure = _reflection.GeneratedProtocolMessageType('KeyFigure', (_message.Message,), {
  'DESCRIPTOR' : _KEYFIGURE,
  '__module__' : 'key_figure_card_pb2'
  # @@protoc_insertion_point(class_scope:KeyFigure)
  })
_sym_db.RegisterMessage(KeyFigure)


# @@protoc_insertion_point(module_scope)
