# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils.key_figure_card_pb2 as key__figure__card__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='statistics.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10statistics.proto\x1a\x15key_figure_card.proto\"L\n\nStatistics\x12\x16\n\x0e\x63\x61rdIdSequence\x18\x01 \x03(\x05\x12&\n\x0ekeyFigureCards\x18\x02 \x03(\x0b\x32\x0e.KeyFigureCardb\x06proto3'
  ,
  dependencies=[key__figure__card__pb2.DESCRIPTOR,])




_STATISTICS = _descriptor.Descriptor(
  name='Statistics',
  full_name='Statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cardIdSequence', full_name='Statistics.cardIdSequence', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyFigureCards', full_name='Statistics.keyFigureCards', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=119,
)

_STATISTICS.fields_by_name['keyFigureCards'].message_type = key__figure__card__pb2._KEYFIGURECARD
DESCRIPTOR.message_types_by_name['Statistics'] = _STATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Statistics = _reflection.GeneratedProtocolMessageType('Statistics', (_message.Message,), {
  'DESCRIPTOR' : _STATISTICS,
  '__module__' : 'statistics_pb2'
  # @@protoc_insertion_point(class_scope:Statistics)
  })
_sym_db.RegisterMessage(Statistics)


# @@protoc_insertion_point(module_scope)
