# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporary_exposure_key_signature_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import temporary_exposure_key_export_pb2 as temporary__exposure__key__export__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporary_exposure_key_signature_list.proto',
  package='SAP.external.exposurenotification',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+temporary_exposure_key_signature_list.proto\x12!SAP.external.exposurenotification\x1a#temporary_exposure_key_export.proto\"W\n\x10TEKSignatureList\x12\x43\n\nsignatures\x18\x01 \x03(\x0b\x32/.SAP.external.exposurenotification.TEKSignature\"\x92\x01\n\x0cTEKSignature\x12H\n\x0esignature_info\x18\x01 \x01(\x0b\x32\x30.SAP.external.exposurenotification.SignatureInfo\x12\x11\n\tbatch_num\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x11\n\tsignature\x18\x04 \x01(\x0c'
  ,
  dependencies=[temporary__exposure__key__export__pb2.DESCRIPTOR,])




_TEKSIGNATURELIST = _descriptor.Descriptor(
  name='TEKSignatureList',
  full_name='SAP.external.exposurenotification.TEKSignatureList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signatures', full_name='SAP.external.exposurenotification.TEKSignatureList.signatures', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=206,
)


_TEKSIGNATURE = _descriptor.Descriptor(
  name='TEKSignature',
  full_name='SAP.external.exposurenotification.TEKSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature_info', full_name='SAP.external.exposurenotification.TEKSignature.signature_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_num', full_name='SAP.external.exposurenotification.TEKSignature.batch_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='SAP.external.exposurenotification.TEKSignature.batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='SAP.external.exposurenotification.TEKSignature.signature', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=355,
)

_TEKSIGNATURELIST.fields_by_name['signatures'].message_type = _TEKSIGNATURE
_TEKSIGNATURE.fields_by_name['signature_info'].message_type = temporary__exposure__key__export__pb2._SIGNATUREINFO
DESCRIPTOR.message_types_by_name['TEKSignatureList'] = _TEKSIGNATURELIST
DESCRIPTOR.message_types_by_name['TEKSignature'] = _TEKSIGNATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TEKSignatureList = _reflection.GeneratedProtocolMessageType('TEKSignatureList', (_message.Message,), {
  'DESCRIPTOR' : _TEKSIGNATURELIST,
  '__module__' : 'temporary_exposure_key_signature_list_pb2'
  # @@protoc_insertion_point(class_scope:SAP.external.exposurenotification.TEKSignatureList)
  })
_sym_db.RegisterMessage(TEKSignatureList)

TEKSignature = _reflection.GeneratedProtocolMessageType('TEKSignature', (_message.Message,), {
  'DESCRIPTOR' : _TEKSIGNATURE,
  '__module__' : 'temporary_exposure_key_signature_list_pb2'
  # @@protoc_insertion_point(class_scope:SAP.external.exposurenotification.TEKSignature)
  })
_sym_db.RegisterMessage(TEKSignature)


# @@protoc_insertion_point(module_scope)
