# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diagnosis_key_batch.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diagnosis_key_batch.proto',
  package='SAP.external.exposurenotification',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x64iagnosis_key_batch.proto\x12!SAP.external.exposurenotification\"R\n\x11\x44iagnosisKeyBatch\x12=\n\x04keys\x18\x01 \x03(\x0b\x32/.SAP.external.exposurenotification.DiagnosisKey\"\x8c\x02\n\x0c\x44iagnosisKey\x12\x0f\n\x07keyData\x18\x01 \x01(\x0c\x12\"\n\x1arollingStartIntervalNumber\x18\x02 \x01(\r\x12\x15\n\rrollingPeriod\x18\x03 \x01(\r\x12\x1d\n\x15transmissionRiskLevel\x18\x04 \x01(\x05\x12\x18\n\x10visitedCountries\x18\x05 \x03(\t\x12\x0e\n\x06origin\x18\x06 \x01(\t\x12\x41\n\nreportType\x18\x07 \x01(\x0e\x32-.SAP.external.exposurenotification.ReportType\x12$\n\x1c\x64\x61ys_since_onset_of_symptoms\x18\x08 \x01(\x11*|\n\nReportType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0e\x43ONFIRMED_TEST\x10\x01\x12 \n\x1c\x43ONFIRMED_CLINICAL_DIAGNOSIS\x10\x02\x12\x0f\n\x0bSELF_REPORT\x10\x03\x12\r\n\tRECURSIVE\x10\x04\x12\x0b\n\x07REVOKED\x10\x05\x62\x06proto3'
)

_REPORTTYPE = _descriptor.EnumDescriptor(
  name='ReportType',
  full_name='SAP.external.exposurenotification.ReportType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIRMED_TEST', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIRMED_CLINICAL_DIAGNOSIS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELF_REPORT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RECURSIVE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVOKED', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=419,
  serialized_end=543,
)
_sym_db.RegisterEnumDescriptor(_REPORTTYPE)

ReportType = enum_type_wrapper.EnumTypeWrapper(_REPORTTYPE)
UNKNOWN = 0
CONFIRMED_TEST = 1
CONFIRMED_CLINICAL_DIAGNOSIS = 2
SELF_REPORT = 3
RECURSIVE = 4
REVOKED = 5



_DIAGNOSISKEYBATCH = _descriptor.Descriptor(
  name='DiagnosisKeyBatch',
  full_name='SAP.external.exposurenotification.DiagnosisKeyBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='SAP.external.exposurenotification.DiagnosisKeyBatch.keys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=146,
)


_DIAGNOSISKEY = _descriptor.Descriptor(
  name='DiagnosisKey',
  full_name='SAP.external.exposurenotification.DiagnosisKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyData', full_name='SAP.external.exposurenotification.DiagnosisKey.keyData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rollingStartIntervalNumber', full_name='SAP.external.exposurenotification.DiagnosisKey.rollingStartIntervalNumber', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rollingPeriod', full_name='SAP.external.exposurenotification.DiagnosisKey.rollingPeriod', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transmissionRiskLevel', full_name='SAP.external.exposurenotification.DiagnosisKey.transmissionRiskLevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visitedCountries', full_name='SAP.external.exposurenotification.DiagnosisKey.visitedCountries', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='origin', full_name='SAP.external.exposurenotification.DiagnosisKey.origin', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reportType', full_name='SAP.external.exposurenotification.DiagnosisKey.reportType', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='days_since_onset_of_symptoms', full_name='SAP.external.exposurenotification.DiagnosisKey.days_since_onset_of_symptoms', index=7,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=417,
)

_DIAGNOSISKEYBATCH.fields_by_name['keys'].message_type = _DIAGNOSISKEY
_DIAGNOSISKEY.fields_by_name['reportType'].enum_type = _REPORTTYPE
DESCRIPTOR.message_types_by_name['DiagnosisKeyBatch'] = _DIAGNOSISKEYBATCH
DESCRIPTOR.message_types_by_name['DiagnosisKey'] = _DIAGNOSISKEY
DESCRIPTOR.enum_types_by_name['ReportType'] = _REPORTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiagnosisKeyBatch = _reflection.GeneratedProtocolMessageType('DiagnosisKeyBatch', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSISKEYBATCH,
  '__module__' : 'diagnosis_key_batch_pb2'
  # @@protoc_insertion_point(class_scope:SAP.external.exposurenotification.DiagnosisKeyBatch)
  })
_sym_db.RegisterMessage(DiagnosisKeyBatch)

DiagnosisKey = _reflection.GeneratedProtocolMessageType('DiagnosisKey', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSISKEY,
  '__module__' : 'diagnosis_key_batch_pb2'
  # @@protoc_insertion_point(class_scope:SAP.external.exposurenotification.DiagnosisKey)
  })
_sym_db.RegisterMessage(DiagnosisKey)


# @@protoc_insertion_point(module_scope)
